SELECT 'ANALYTICS.CISCO_SL_TABLE' AS Tab, MAX(INTERV) AS Date_time
FROM ANALYTICS.CISCO_SL_TABLE
WHERE INTERV >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.CISCO_OPERATOR' AS Tab, MAX(DATETIME) AS Date_time
FROM ANALYTICS.CISCO_OPERATOR
WHERE DATETIME >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.TOLOG_ISXOD_CISCO_DDO' AS Tab, MAX(Origination) AS Date_time
FROM ANALYTICS.TOLOG_ISXOD_CISCO_DDO
WHERE Origination >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.TOLOG_CHAT_TIME_ONE' AS Tab, MAX(DTM_DIALOG) AS Date_time
FROM ANALYTICS.TOLOG_CHAT_TIME_ONE
WHERE DTM_DIALOG >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.TOLOG_RETENTIONS_CHATS_TABLE' AS Tab, MAX(created) AS Date_time
FROM ANALYTICS.TOLOG_RETENTIONS_CHATS_TABLE
WHERE created >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.TOLOG_RETENTIONS_CALLS_TABLE' AS Tab, MAX(DT) AS Date_time
FROM ANALYTICS.TOLOG_RETENTIONS_CALLS_TABLE
WHERE DT >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.TOLOG_CHAT_TIME_TWO' AS Tab, MAX(CREATED) AS Date_time
FROM ANALYTICS.TOLOG_CHAT_TIME_TWO
WHERE CREATED >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.TOLOG_CLOSED_CARDS_AND_PACKAGES_ON_CALL' AS Tab, MAX(TIME_CLOSE) AS Date_time
FROM ANALYTICS.TOLOG_CLOSED_CARDS_AND_PACKAGES_ON_CALL
WHERE TIME_CLOSE >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.TOLOG_CISCO_OPERATOR_STATE' AS Tab, MAX(DATE_) AS Date_time
FROM ANALYTICS.TOLOG_CISCO_OPERATOR_STATE
WHERE DATE_ >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.TOLOG_TRANSFERRED_CALLS' AS Tab, MAX(DATE_FROM) AS Date_time
FROM ANALYTICS.TOLOG_TRANSFERRED_CALLS
WHERE DATE_FROM >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.TOLOG_CISCO_MONITORING_SKILL_30' AS Tab, MAX(INTERVAL) AS Date_time
FROM ANALYTICS.TOLOG_CISCO_MONITORING_SKILL_30
WHERE INTERVAL >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.TOLOG_ISXOD_CISCO_MONITORING' AS Tab, MAX(Origination) AS Date_time
FROM ANALYTICS.TOLOG_ISXOD_CISCO_MONITORING
WHERE Origination >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.TOLOG_ONECTA_BI_TABLE' AS Tab, MAX(DATE_HOUR) AS Date_time
FROM ANALYTICS.TOLOG_ONECTA_BI_TABLE
WHERE DATE_HOUR >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.TOLOG_CALLS_THEMS_V1' AS Tab, MAX(DT_DAY) AS Date_time
FROM ANALYTICS.TOLOG_CALLS_THEMS_V1
WHERE DT_DAY >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.TOLOG_CHATS_THEMS' AS Tab, MAX(CREATED) AS Date_time
FROM ANALYTICS.TOLOG_CHATS_THEMS
WHERE CREATED >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.TOLOG_RETENTIONS_FINALLY_TABLE' AS Tab, MAX(DATE_CREATED) AS Date_time
FROM ANALYTICS.TOLOG_RETENTIONS_FINALLY_TABLE
WHERE DATE_CREATED >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.TOLOG_CHAT_HOLD' AS Tab, MAX(DTM) AS Date_time
FROM ANALYTICS.TOLOG_CHAT_HOLD
WHERE DTM >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.TOLOG_CHAT_HOLD_V2' AS Tab, MAX(DTM) AS Date_time
FROM ANALYTICS.TOLOG_CHAT_HOLD_V2
WHERE DTM >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.TOLOG_WEBIM_CHAT_TABLE' AS Tab, MAX(DT) AS Date_time
FROM ANALYTICS.TOLOG_WEBIM_CHAT_TABLE
WHERE DT >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.TOLOG_WEBIM_CHAT_RETURN' AS Tab, MAX(DT) AS Date_time
FROM ANALYTICS.TOLOG_WEBIM_CHAT_RETURN
WHERE DT >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.TOLOG_IVR_QE' AS Tab, MAX(TIMESTAMP_) AS Date_time
FROM ANALYTICS.TOLOG_IVR_QE
WHERE TIMESTAMP_ >= TRUNC(SYSDATE - 1)

UNION ALL

SELECT 'ANALYTICS.TOLOG_DNT' AS Tab, MAX(CREATED_TZ) AS Date_time
FROM ANALYTICS.TOLOG_DNT
WHERE CREATED_TZ >= TRUNC(SYSDATE - 1);
