CREATE TABLE tmp_stats_service_level (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    threadid NUMBER NOT NULL,
    department_id NUMBER,
    got_into_common_queue_time DATE NOT NULL,
    start_chatting_time DATE NOT NULL,
    PRIMARY KEY (id)
)
