WITH schedule_hours AS (
    SELECT DATE_SCHEDULE + (LEVEL - 1)/24 AS HOUR_INTERVAL
    FROM dual
    CONNECT BY LEVEL <= 24
),
employee_schedules AS (
    SELECT
        FIO,
        TO_DATE(START_SCHEDULE, 'HH24:MI') AS START_TIME,
        TO_DATE(END_SCHEDULE, 'HH24:MI') AS END_TIME,
        DATE_SCHEDULE
    FROM your_table
)
SELECT
    sh.HOUR_INTERVAL,
    COUNT(es.FIO) AS EMPLOYEE_COUNT
FROM
    schedule_hours sh
LEFT JOIN employee_schedules es
    ON sh.HOUR_INTERVAL BETWEEN es.DATE_SCHEDULE + (EXTRACT(HOUR FROM es.START_TIME) / 24) 
    AND es.DATE_SCHEDULE + (EXTRACT(HOUR FROM es.END_TIME) / 24)
GROUP BY
    sh.HOUR_INTERVAL
ORDER BY
    sh.HOUR_INTERVAL;

