MAX(TYPE) KEEP (DENSE_RANK LAST ORDER BY DATE_CREATED) AS TYPE, 
MAX(DATE_CREATED) AS DATE_CREATED, 
MAX(ID) KEEP (DENSE_RANK LAST ORDER BY DATE_CREATED) AS ID, 
CLIENT_FIO, 
CLIENT_DID, 
MAX(IBSO_ID_OR_CALLED_FROM_NUM) KEEP (DENSE_RANK LAST ORDER BY DATE_CREATED) AS IBSO_ID_OR_CALLED_FROM_NUM, 
MAX(CARD_TYPE) KEEP (DENSE_RANK LAST ORDER BY DATE_CREATED) AS CARD_TYPE,
MAX(HAVE_REDIRECT) AS HAVE_REDIRECT,
MAX(MONEY) AS MONEY
